-- Warehouses per workspace (same tenancy/RLS model as categories).

CREATE TABLE IF NOT EXISTS public.warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  location TEXT,
  aisle TEXT,
  shelf TEXT,
  level TEXT,
  "position" TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.warehouses
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_warehouses_workspace_id
  ON public.warehouses(workspace_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_warehouses_workspace_name_normalized
  ON public.warehouses(workspace_id, LOWER(BTRIM(name)));

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'update_warehouses_updated_at'
  ) THEN
    CREATE TRIGGER update_warehouses_updated_at
    BEFORE UPDATE ON public.warehouses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouses FORCE ROW LEVEL SECURITY;

CREATE POLICY warehouses_select_policy
  ON public.warehouses
  FOR SELECT
  USING (
    app.is_active_workspace_member(workspace_id)
  );

CREATE POLICY warehouses_insert_policy
  ON public.warehouses
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY warehouses_update_policy
  ON public.warehouses
  FOR UPDATE
  USING (
    app.is_workspace_admin(workspace_id)
  )
  WITH CHECK (
    app.is_workspace_admin(workspace_id)
  );

CREATE POLICY warehouses_delete_policy
  ON public.warehouses
  FOR DELETE
  USING (
    app.is_workspace_admin(workspace_id)
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.warehouses TO authenticated;
REVOKE ALL ON public.warehouses FROM anon;

-- Extend anonymous trial purge to remove warehouse rows for expired anonymous users.
CREATE OR REPLACE FUNCTION public.purge_expired_anonymous_trial_data()
RETURNS TABLE (categories_deleted BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  n BIGINT := 0;
BEGIN
  DELETE FROM public.categories c
  USING auth.users u
  WHERE c.created_by = u.id
    AND u.created_at < NOW() - INTERVAL '30 days'
    AND (
      COALESCE((u.raw_app_meta_data->>'is_anonymous')::boolean, false) = true
      OR (u.raw_app_meta_data->>'provider') = 'anonymous'
    );
  GET DIAGNOSTICS n = ROW_COUNT;

  DELETE FROM public.warehouses w
  USING auth.users u
  WHERE w.created_by = u.id
    AND u.created_at < NOW() - INTERVAL '30 days'
    AND (
      COALESCE((u.raw_app_meta_data->>'is_anonymous')::boolean, false) = true
      OR (u.raw_app_meta_data->>'provider') = 'anonymous'
    );

  DELETE FROM public.workspace_memberships wm
  USING auth.users u
  WHERE wm.user_id = u.id
    AND u.created_at < NOW() - INTERVAL '30 days'
    AND (
      COALESCE((u.raw_app_meta_data->>'is_anonymous')::boolean, false) = true
      OR (u.raw_app_meta_data->>'provider') = 'anonymous'
    );

  DELETE FROM public.workspaces w
  WHERE NOT EXISTS (
    SELECT 1 FROM public.workspace_memberships m WHERE m.workspace_id = w.id
  );

  RETURN QUERY SELECT n;
END;
$$;
