-- Products and variants schema with workspace-aware RLS.

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.products
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_products_workspace_id
  ON public.products(workspace_id);

CREATE INDEX IF NOT EXISTS idx_products_category_id
  ON public.products(category_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_products_workspace_name_normalized
  ON public.products(workspace_id, LOWER(BTRIM(name)));

CREATE TABLE IF NOT EXISTS public.product_option_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  input_kind TEXT NOT NULL DEFAULT 'text' CHECK (input_kind IN ('text', 'numeric')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.product_option_types
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_product_option_types_workspace_id
  ON public.product_option_types(workspace_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_option_types_workspace_name_normalized
  ON public.product_option_types(workspace_id, LOWER(BTRIM(name)));

CREATE TABLE IF NOT EXISTS public.product_option_values (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  option_type_id BIGINT NOT NULL REFERENCES public.product_option_types(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  value TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.product_option_values
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_product_option_values_workspace_id
  ON public.product_option_values(workspace_id);

CREATE INDEX IF NOT EXISTS idx_product_option_values_option_type_id
  ON public.product_option_values(option_type_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_option_values_workspace_type_value_normalized
  ON public.product_option_values(workspace_id, option_type_id, LOWER(BTRIM(value)));

CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  barcode TEXT,
  unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  cost_price NUMERIC(12, 2) CHECK (cost_price IS NULL OR cost_price >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.product_variants
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_product_variants_workspace_id
  ON public.product_variants(workspace_id);

CREATE INDEX IF NOT EXISTS idx_product_variants_product_id
  ON public.product_variants(product_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_variants_workspace_sku_normalized
  ON public.product_variants(workspace_id, LOWER(BTRIM(sku)));

CREATE TABLE IF NOT EXISTS public.product_variant_option_values (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  variant_id BIGINT NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  option_type_id BIGINT NOT NULL REFERENCES public.product_option_types(id) ON DELETE CASCADE,
  option_value_id BIGINT NOT NULL REFERENCES public.product_option_values(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.product_variant_option_values
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_product_variant_option_values_workspace_id
  ON public.product_variant_option_values(workspace_id);

CREATE INDEX IF NOT EXISTS idx_product_variant_option_values_variant_id
  ON public.product_variant_option_values(variant_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_variant_option_values_variant_type
  ON public.product_variant_option_values(variant_id, option_type_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_variant_option_values_variant_value
  ON public.product_variant_option_values(variant_id, option_value_id);

CREATE TABLE IF NOT EXISTS public.variant_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  variant_id BIGINT NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  warehouse_id BIGINT NOT NULL REFERENCES public.warehouses(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  reorder_level NUMERIC(14, 3) CHECK (reorder_level IS NULL OR reorder_level >= 0),
  alert_active BOOLEAN NOT NULL DEFAULT FALSE,
  alert_method TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.variant_inventory
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_variant_inventory_workspace_id
  ON public.variant_inventory(workspace_id);

CREATE INDEX IF NOT EXISTS idx_variant_inventory_variant_id
  ON public.variant_inventory(variant_id);

CREATE INDEX IF NOT EXISTS idx_variant_inventory_warehouse_id
  ON public.variant_inventory(warehouse_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_variant_inventory_variant_warehouse
  ON public.variant_inventory(variant_id, warehouse_id);

CREATE TABLE IF NOT EXISTS public.variant_inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  variant_inventory_id BIGINT REFERENCES public.variant_inventory(id) ON DELETE SET NULL,
  variant_id BIGINT NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movement_type TEXT NOT NULL CHECK (movement_type IN ('entry', 'exit', 'transfer', 'adjustment')),
  quantity_moved NUMERIC(14, 3) NOT NULL CHECK (quantity_moved > 0),
  source_warehouse_id BIGINT REFERENCES public.warehouses(id) ON DELETE SET NULL,
  destination_warehouse_id BIGINT REFERENCES public.warehouses(id) ON DELETE SET NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_variant_inventory_movements_transfer_destination
    CHECK (
      movement_type <> 'transfer'
      OR destination_warehouse_id IS NOT NULL
    )
);

ALTER TABLE public.variant_inventory_movements
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_variant_inventory_movements_workspace_id
  ON public.variant_inventory_movements(workspace_id);

CREATE INDEX IF NOT EXISTS idx_variant_inventory_movements_variant_id
  ON public.variant_inventory_movements(variant_id);

CREATE INDEX IF NOT EXISTS idx_variant_inventory_movements_created_at
  ON public.variant_inventory_movements(created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_products_updated_at'
  ) THEN
    CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_product_option_types_updated_at'
  ) THEN
    CREATE TRIGGER update_product_option_types_updated_at
    BEFORE UPDATE ON public.product_option_types
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_product_option_values_updated_at'
  ) THEN
    CREATE TRIGGER update_product_option_values_updated_at
    BEFORE UPDATE ON public.product_option_values
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_product_variants_updated_at'
  ) THEN
    CREATE TRIGGER update_product_variants_updated_at
    BEFORE UPDATE ON public.product_variants
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_variant_inventory_updated_at'
  ) THEN
    CREATE TRIGGER update_variant_inventory_updated_at
    BEFORE UPDATE ON public.variant_inventory
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_variant_inventory_movements_updated_at'
  ) THEN
    CREATE TRIGGER update_variant_inventory_movements_updated_at
    BEFORE UPDATE ON public.variant_inventory_movements
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products FORCE ROW LEVEL SECURITY;
ALTER TABLE public.product_option_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_option_types FORCE ROW LEVEL SECURITY;
ALTER TABLE public.product_option_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_option_values FORCE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants FORCE ROW LEVEL SECURITY;
ALTER TABLE public.product_variant_option_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variant_option_values FORCE ROW LEVEL SECURITY;
ALTER TABLE public.variant_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variant_inventory FORCE ROW LEVEL SECURITY;
ALTER TABLE public.variant_inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.variant_inventory_movements FORCE ROW LEVEL SECURITY;

CREATE POLICY products_select_policy
  ON public.products
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY products_insert_policy
  ON public.products
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY products_update_policy
  ON public.products
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY products_delete_policy
  ON public.products
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY product_option_types_select_policy
  ON public.product_option_types
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY product_option_types_insert_policy
  ON public.product_option_types
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY product_option_types_update_policy
  ON public.product_option_types
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY product_option_types_delete_policy
  ON public.product_option_types
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY product_option_values_select_policy
  ON public.product_option_values
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY product_option_values_insert_policy
  ON public.product_option_values
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY product_option_values_update_policy
  ON public.product_option_values
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY product_option_values_delete_policy
  ON public.product_option_values
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY product_variants_select_policy
  ON public.product_variants
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY product_variants_insert_policy
  ON public.product_variants
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY product_variants_update_policy
  ON public.product_variants
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY product_variants_delete_policy
  ON public.product_variants
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY product_variant_option_values_select_policy
  ON public.product_variant_option_values
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY product_variant_option_values_insert_policy
  ON public.product_variant_option_values
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY product_variant_option_values_update_policy
  ON public.product_variant_option_values
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY product_variant_option_values_delete_policy
  ON public.product_variant_option_values
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY variant_inventory_select_policy
  ON public.variant_inventory
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY variant_inventory_insert_policy
  ON public.variant_inventory
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY variant_inventory_update_policy
  ON public.variant_inventory
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY variant_inventory_delete_policy
  ON public.variant_inventory
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY variant_inventory_movements_select_policy
  ON public.variant_inventory_movements
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY variant_inventory_movements_insert_policy
  ON public.variant_inventory_movements
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY variant_inventory_movements_update_policy
  ON public.variant_inventory_movements
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY variant_inventory_movements_delete_policy
  ON public.variant_inventory_movements
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_option_types TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_option_values TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_variants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_variant_option_values TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.variant_inventory TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.variant_inventory_movements TO authenticated;

REVOKE ALL ON public.products FROM anon;
REVOKE ALL ON public.product_option_types FROM anon;
REVOKE ALL ON public.product_option_values FROM anon;
REVOKE ALL ON public.product_variants FROM anon;
REVOKE ALL ON public.product_variant_option_values FROM anon;
REVOKE ALL ON public.variant_inventory FROM anon;
REVOKE ALL ON public.variant_inventory_movements FROM anon;
