-- Sales schema with workspace-aware RLS and integrity guards.

CREATE TABLE IF NOT EXISTS public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  warehouse_id BIGINT REFERENCES public.warehouses(id) ON DELETE SET NULL,
  customer_name TEXT,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('draft', 'completed', 'voided')),
  notes TEXT,
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  discount_total NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
  tax_total NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
  total NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  paid_total NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (paid_total >= 0),
  change_total NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (change_total >= 0),
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  sold_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.sales
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_sales_workspace_id
  ON public.sales(workspace_id);

CREATE INDEX IF NOT EXISTS idx_sales_warehouse_id
  ON public.sales(warehouse_id);

CREATE INDEX IF NOT EXISTS idx_sales_sold_at
  ON public.sales(sold_at DESC);

CREATE TABLE IF NOT EXISTS public.sale_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  sale_id BIGINT NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  variant_id BIGINT NOT NULL REFERENCES public.product_variants(id) ON DELETE RESTRICT,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  quantity NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
  applied_unit_price NUMERIC(12, 2) NOT NULL CHECK (applied_unit_price >= 0),
  applied_cost_price NUMERIC(12, 2) CHECK (applied_cost_price IS NULL OR applied_cost_price >= 0),
  line_subtotal NUMERIC(12, 2) NOT NULL CHECK (line_subtotal >= 0),
  line_total NUMERIC(12, 2) NOT NULL CHECK (line_total >= 0),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.sale_lines
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_sale_lines_workspace_id
  ON public.sale_lines(workspace_id);

CREATE INDEX IF NOT EXISTS idx_sale_lines_sale_id
  ON public.sale_lines(sale_id);

CREATE INDEX IF NOT EXISTS idx_sale_lines_variant_id
  ON public.sale_lines(variant_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sale_lines_sale_variant
  ON public.sale_lines(sale_id, variant_id);

CREATE TABLE IF NOT EXISTS public.sale_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  sale_id BIGINT NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('cash', 'card', 'transfer', 'other')),
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  reference_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.sale_payments
  ALTER COLUMN created_by SET DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_sale_payments_workspace_id
  ON public.sale_payments(workspace_id);

CREATE INDEX IF NOT EXISTS idx_sale_payments_sale_id
  ON public.sale_payments(sale_id);

CREATE INDEX IF NOT EXISTS idx_sale_payments_payment_method
  ON public.sale_payments(payment_method);

CREATE OR REPLACE FUNCTION app.enforce_sales_workspace_match()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_warehouse_workspace_id UUID;
BEGIN
  IF NEW.warehouse_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT w.workspace_id
  INTO v_warehouse_workspace_id
  FROM public.warehouses w
  WHERE w.id = NEW.warehouse_id;

  IF v_warehouse_workspace_id IS NULL THEN
    RAISE EXCEPTION 'Invalid warehouse_id % for sales', NEW.warehouse_id;
  END IF;

  IF NEW.workspace_id <> v_warehouse_workspace_id THEN
    RAISE EXCEPTION 'Workspace mismatch: sales.warehouse_id belongs to a different workspace';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION app.enforce_sale_lines_workspace_match()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_sale_workspace_id UUID;
  v_variant_workspace_id UUID;
BEGIN
  SELECT s.workspace_id
  INTO v_sale_workspace_id
  FROM public.sales s
  WHERE s.id = NEW.sale_id;

  SELECT pv.workspace_id
  INTO v_variant_workspace_id
  FROM public.product_variants pv
  WHERE pv.id = NEW.variant_id;

  IF v_sale_workspace_id IS NULL THEN
    RAISE EXCEPTION 'Invalid sale_id % for sale_lines', NEW.sale_id;
  END IF;

  IF v_variant_workspace_id IS NULL THEN
    RAISE EXCEPTION 'Invalid variant_id % for sale_lines', NEW.variant_id;
  END IF;

  IF NEW.workspace_id <> v_sale_workspace_id
     OR NEW.workspace_id <> v_variant_workspace_id THEN
    RAISE EXCEPTION 'Workspace mismatch in sale_lines relation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION app.enforce_sale_payments_workspace_match()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_sale_workspace_id UUID;
BEGIN
  SELECT s.workspace_id
  INTO v_sale_workspace_id
  FROM public.sales s
  WHERE s.id = NEW.sale_id;

  IF v_sale_workspace_id IS NULL THEN
    RAISE EXCEPTION 'Invalid sale_id % for sale_payments', NEW.sale_id;
  END IF;

  IF NEW.workspace_id <> v_sale_workspace_id THEN
    RAISE EXCEPTION 'Workspace mismatch: sale_payments.workspace_id must match sales.workspace_id';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_sales_workspace_match ON public.sales;
CREATE TRIGGER trg_enforce_sales_workspace_match
BEFORE INSERT OR UPDATE ON public.sales
FOR EACH ROW
EXECUTE FUNCTION app.enforce_sales_workspace_match();

DROP TRIGGER IF EXISTS trg_enforce_sale_lines_workspace_match ON public.sale_lines;
CREATE TRIGGER trg_enforce_sale_lines_workspace_match
BEFORE INSERT OR UPDATE ON public.sale_lines
FOR EACH ROW
EXECUTE FUNCTION app.enforce_sale_lines_workspace_match();

DROP TRIGGER IF EXISTS trg_enforce_sale_payments_workspace_match ON public.sale_payments;
CREATE TRIGGER trg_enforce_sale_payments_workspace_match
BEFORE INSERT OR UPDATE ON public.sale_payments
FOR EACH ROW
EXECUTE FUNCTION app.enforce_sale_payments_workspace_match();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'update_sales_updated_at'
  ) THEN
    CREATE TRIGGER update_sales_updated_at
    BEFORE UPDATE ON public.sales
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales FORCE ROW LEVEL SECURITY;
ALTER TABLE public.sale_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_lines FORCE ROW LEVEL SECURITY;
ALTER TABLE public.sale_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_payments FORCE ROW LEVEL SECURITY;

CREATE POLICY sales_select_policy
  ON public.sales
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY sales_insert_policy
  ON public.sales
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY sales_update_policy
  ON public.sales
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY sales_delete_policy
  ON public.sales
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY sale_lines_select_policy
  ON public.sale_lines
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY sale_lines_insert_policy
  ON public.sale_lines
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY sale_lines_update_policy
  ON public.sale_lines
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY sale_lines_delete_policy
  ON public.sale_lines
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

CREATE POLICY sale_payments_select_policy
  ON public.sale_payments
  FOR SELECT
  USING (app.is_active_workspace_member(workspace_id));

CREATE POLICY sale_payments_insert_policy
  ON public.sale_payments
  FOR INSERT
  WITH CHECK (
    app.is_workspace_editor(workspace_id)
    AND COALESCE(created_by, app.current_user_id()) = app.current_user_id()
  );

CREATE POLICY sale_payments_update_policy
  ON public.sale_payments
  FOR UPDATE
  USING (app.is_workspace_admin(workspace_id))
  WITH CHECK (app.is_workspace_admin(workspace_id));

CREATE POLICY sale_payments_delete_policy
  ON public.sale_payments
  FOR DELETE
  USING (app.is_workspace_admin(workspace_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.sales TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sale_lines TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sale_payments TO authenticated;

REVOKE ALL ON public.sales FROM anon;
REVOKE ALL ON public.sale_lines FROM anon;
REVOKE ALL ON public.sale_payments FROM anon;
